name: expensease
description: A new Flutter project for managing shared expenses effortlessly.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  cloud_functions: ^4.6.9

  # State Management & Routing
  get: ^4.6.6
  get_storage: ^2.1.1

  # UI & UX
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4
  fl_chart: ^1.0.0
  shimmer: ^3.0.0

  # Utility Packages
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.6
  http: ^1.2.1

  # PDF & Printing
  pdf: ^3.10.8
  printing: ^5.12.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  share_plus: ^10.0.0
  flutter_speed_dial: ^7.0.0
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/app_icon.png