// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPuONMUu6dyaHWmbGaG1vGItZfH2Ae4ic',
    appId: '1:894658948129:web:2522971242fc1a91298760',
    messagingSenderId: '894658948129',
    projectId: 'expensease-886ec',
    authDomain: 'expensease-886ec.firebaseapp.com',
    storageBucket: 'expensease-886ec.firebasestorage.app',
    measurementId: 'G-C9B0VNJQL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBue8WWbb0aT_8u-qsgZd7EJth-Bq906AE',
    appId: '1:894658948129:android:e0c231d0e10bfd81298760',
    messagingSenderId: '894658948129',
    projectId: 'expensease-886ec',
    storageBucket: 'expensease-886ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMwY0AFAszkuBIyWqV40ROSwzXFW-W-RU',
    appId: '1:894658948129:ios:9e1c2e87bf591a90298760',
    messagingSenderId: '894658948129',
    projectId: 'expensease-886ec',
    storageBucket: 'expensease-886ec.firebasestorage.app',
    iosBundleId: 'com.example.expensease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMwY0AFAszkuBIyWqV40ROSwzXFW-W-RU',
    appId: '1:894658948129:ios:9e1c2e87bf591a90298760',
    messagingSenderId: '894658948129',
    projectId: 'expensease-886ec',
    storageBucket: 'expensease-886ec.firebasestorage.app',
    iosBundleId: 'com.example.expensease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPuONMUu6dyaHWmbGaG1vGItZfH2Ae4ic',
    appId: '1:894658948129:web:faf374efd4115dfc298760',
    messagingSenderId: '894658948129',
    projectId: 'expensease-886ec',
    authDomain: 'expensease-886ec.firebaseapp.com',
    storageBucket: 'expensease-886ec.firebasestorage.app',
    measurementId: 'G-KME3KJ8C6L',
  );
}
